package cli

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/jinyongp/devtools/internal/protocol"
)

func (a *App) registerCompletion() {
	a.commands = append(a.commands, Command{Name: "completion", Description: "Generate shell completion for zsh, bash, or fish.", Arguments: []Argument{{Name: "shell", Required: true, Pattern: "^(zsh|bash|fish)$"}}, StreamOutput: true, Output: map[string]any{"type": "string"}, Run: func(_ context.Context, streams IO, r Request) (any, *protocol.Error) {
		if err := writeHelp(streams.Out, a.completionScript(r.Args[0])); err != nil {
			return nil, protocol.NewError("io_error", "Cannot write completion script.", 1, nil)
		}
		return processResult{ExitCode: 0}, nil
	}})
}

type completionNode struct {
	children map[string]string
	options  map[string]Option
}

func shellQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'" }

// Only command metadata is used: generation never opens project or value stores.
func (a *App) completionScript(shell string) string {
	nodes := map[string]*completionNode{}
	node := func(path string) *completionNode {
		if nodes[path] == nil {
			nodes[path] = &completionNode{map[string]string{}, map[string]Option{}}
		}
		return nodes[path]
	}
	node("").options["--version"] = Option{Boolean: true, Description: "Show version"}
	for _, cmd := range a.commands {
		for _, name := range append([]string{cmd.Name}, cmd.Aliases...) {
			parts := strings.Fields(name)
			for i, part := range parts {
				parent := strings.Join(parts[:i], " ")
				path := strings.Join(parts[:i+1], " ")
				node(parent).children[part] = a.commandSummary(path)
				node(path)
			}
			for _, opt := range cmd.Options {
				node(name).options["--"+opt.Name] = opt
			}
		}
	}
	for _, sh := range []string{"bash", "fish", "zsh"} {
		node("completion").children[sh] = "Generate " + sh + " completion"
		node("completion " + sh)
	}
	paths := make([]string, 0, len(nodes))
	for path, n := range nodes {
		paths = append(paths, path)
		n.options["--help"] = Option{Boolean: true, Description: "Show help"}
		n.options["-h"] = n.options["--help"]
	}
	sort.Strings(paths)
	var b strings.Builder
	if shell == "fish" {
		b.WriteString("# Generated by devtools completion fish\nfunction __devtools_candidates\n  set -l ctx ''\n  set -l skip 0\n  set -l words (commandline -opc)\n  for word in $words[2..-1]\n    if test $skip = 1\n      set skip 0\n      continue\n    end\n    switch $word\n      case --\n        return\n      case '--*=*'\n        continue\n    end\n    switch \"$ctx|$word\"\n")
	} else {
		if shell == "zsh" {
			b.WriteString("#compdef devtools\n")
		}
		b.WriteString("_devtools() {\n  local ctx='' skip=0 word i\n")
		if shell == "bash" {
			b.WriteString("  COMPREPLY=()\n  local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n  for ((i=1; i<COMP_CWORD; i++)); do\n    word=${COMP_WORDS[i]}\n")
		} else {
			b.WriteString("  local -a candidates\n  for ((i=2; i<CURRENT; i++)); do\n    word=${words[i]}\n")
		}
		b.WriteString("    if [[ $skip == 1 ]]; then skip=0; continue; fi\n    case $word in --) return;; --*=*) continue;; esac\n    case \"$ctx|$word\" in\n")
	}
	for _, path := range paths {
		n := nodes[path]
		keys := make([]string, 0, len(n.children)+len(n.options))
		for k := range n.children {
			keys = append(keys, k)
		}
		for k := range n.options {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			key := shellQuote(path + "|" + k)
			value := strings.TrimSpace(path + " " + k)
			opt, isOption := n.options[k]
			if shell == "fish" {
				fmt.Fprintf(&b, "      case %s\n", key)
				if !isOption {
					fmt.Fprintf(&b, "        set ctx %s\n", shellQuote(value))
				} else if !opt.Boolean {
					b.WriteString("        set skip 1\n")
				}
			} else {
				fmt.Fprintf(&b, "      %s) ", key)
				if !isOption {
					fmt.Fprintf(&b, "ctx=%s", shellQuote(value))
				} else if !opt.Boolean {
					b.WriteString("skip=1")
				} else {
					b.WriteString(":")
				}
				b.WriteString(";;\n")
			}
		}
	}
	if shell == "fish" {
		b.WriteString("      case '-*' '*|-*'\n        return\n    end\n  end\n  test $skip = 0; or return\n  switch $ctx\n")
	} else {
		b.WriteString("      *'|-'*) return;;\n    esac\n  done\n  [[ $skip == 0 ]] || return\n  case $ctx in\n")
	}
	for _, path := range paths {
		n := nodes[path]
		candidates := map[string]string{}
		for k, v := range n.children {
			candidates[k] = v
		}
		for k, v := range n.options {
			candidates[k] = v.Description
		}
		keys := make([]string, 0, len(candidates))
		for k := range candidates {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		if shell == "fish" {
			fmt.Fprintf(&b, "    case %s\n", shellQuote(path))
			for _, k := range keys {
				fmt.Fprintf(&b, "      printf '%%s\\t%%s\\n' %s %s\n", shellQuote(k), shellQuote(candidates[k]))
			}
		} else if shell == "bash" {
			fmt.Fprintf(&b, "    %s) COMPREPLY=( $(compgen -W %s -- \"$cur\") );;\n", shellQuote(path), shellQuote(strings.Join(keys, " ")))
		} else {
			fmt.Fprintf(&b, "    %s) candidates=(", shellQuote(path))
			for _, k := range keys {
				fmt.Fprintf(&b, " %s", shellQuote(k+":"+strings.ReplaceAll(candidates[k], ":", "\\:")))
			}
			b.WriteString(" );;\n")
		}
	}
	if shell == "fish" {
		b.WriteString("  end\nend\ncomplete -c devtools -f -a '(__devtools_candidates)'\n")
	} else if shell == "bash" {
		b.WriteString("  esac\n}\ncomplete -F _devtools devtools\n")
	} else {
		b.WriteString("  esac\n  _describe 'devtools' candidates\n}\nif [[ $funcstack[1] == _devtools ]]; then\n  _devtools \"$@\"\nelse\n  compdef _devtools devtools\nfi\n")
	}
	return b.String()
}
