name: auto-merge homebrew-tap updates

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: jinyongp/homebrew-tap/.github/workflows/auto-merge-homebrew-tap.yml@1f250b93ce0d9ca875356948a953b7cfd2accf82
