name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v4
        with:
          just-version: '1.58.0'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.27.x'
          check-latest: true
          cache: true
      - run: just check
      - run: just build
      - run: ./bin/devtools project inspect
